name: GitHub-Profile-3D-Contrib

on:
  schedule: # 18:00 KST == 09:00 UTC on every Sunday
    - cron: "0 9 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_3D }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "minsuhan1"
          git config user.email "trms7794han@gmail.com"
          git add -A .
          git commit -m "generated"
          git push
